const USUARIO_PLANOS = {
  PF_FREE: 'PF_FREE',
  PF_SMART: 'PF_SMART',
  PF_PREMIUM: 'PF_PREMIUM',
  PJ_FREE: 'PJ_FREE',
  PJ_SMART: 'PJ_SMART',
  PJ_PREMIUM: 'PJ_PREMIUM',
  PJ_ENTERPRISE: 'PJ_ENTERPRISE',
  MASTER_ADMIN: 'MASTER_ADMIN',
}

module.exports = {
  USUARIO_PLANOS,
}