exports.USUARIO_PLANOS = {
  PF_FREE: "PF_FREE",
  PF_SMART: "PF_SMART",
  PF_PREMIUM: "PF_PREMIUM",
  PJ_FREE: "PJ_FREE",
  PJ_SMART: "PJ_SMART",
  PJ_PREMIUM: "PJ_PREMIUM",
  PJ_ENTERPRISE: "PJ_ENTERPRISE",
  MASTER_ADMIN: "MASTER_ADMIN",
};

exports.TIPO_TELEFONE = {
  FIXO: "FIXO",
  CELULAR: "CELULAR",
  WHATSAPP: "WHATSAPP",
  TELEGRAM: "TELEGRAM",
  OUTRO: "OUTRO",
};

exports.TIPO_DOCUMENTO = {
  CPF: "CPF",
  RG: "RG",
  PASSAPORTE: "PASSAPORTE",
  CNH: "CNH",
  CNPJ: "CNPJ",
  INSCRICAO_ESTADUAL: "INSCRICAO_ESTADUAL",
};

exports.TIPO_LINK = {
  WEBSITE: "WEBSITE",
  LINKEDIN: "LINKEDIN",
  FACEBOOK: "FACEBOOK",
  INSTAGRAM: "INSTAGRAM",
  TWITTER: "TWITTER",
  YOUTUBE: "YOUTUBE",
  OUTRO: "OUTRO",
};

exports.FLUENCIA_LINGUAGEM = {
  NENHUMA: "NENHUMA",
  BASICA: "BASICA",
  INTERMEDIARIA: "INTERMEDIARIA",
  PROFICIENTE: "PROFICIENTE",
  FLUENTE: "FLUENTE",
};

exports.TIPO_ESCOLARIDADE = {
  FUNDAMENTAL: "FUNDAMENTAL",
  ENSINO_MEDIO: "ENSINO_MEDIO",
  SUPERIOR: "SUPERIOR",
  MESTRADO: "MESTRADO",
  DOUTORADO: "DOUTORADO",
};

exports.TIPO_GENERO = {
  NAO_ESPECIFICADO: "NAO_ESPECIFICADO",
  MASCULINO: "MASCULINO",
  FEMININO: "FEMININO",
  OUTRO: "OUTRO",
}

exports.TIPO_ESTADO_CIVIL = {
  SOLTEIRO: "SOLTEIRO",
  CASADO: "CASADO",
  UNIAO_ESTAVEL: "UNIAO_ESTAVEL",
  VIUVO: "VIUVO",
  OUTRO: "OUTRO",
}

exports.TIPO_CNH = {
  NONE: "NONE",
  // A: "A (moto)",
  // B: "B (carro)",
  // C: "C (caminhão)",
  // D: "D (micro ônibus)",
  // E: "E (articulados)",
  // AB: "A e B (moto + carro)",
  // AC: "A e C (moto + caminhão)",
  // AD: "A e D (moto + micro ônibus)",
  // AE: "A e E (moto + articulados)",
  A: "A",
  B: "B",
  C: "C",
  D: "D",
  E: "E",
  AB: "AB",
  AC: "AC",
  AD: "AD",
  AE: "AE",
}

exports.TIPO_QUESTAO = {
  TEXTO: 'TEXTO',
}